theme: jekyll-theme-cayman

title: Gated Gradient Flow
description: Project page for the ICML2021 paper Learning Node Representations Using Stationary Flow Prediction on Large Payment and Cash Transaction Networks.

buttons:
  paper_url: http://proceedings.mlr.press/v139/ceylan21a
  paper_title: Paper
  data_url: https://kth-my.sharepoint.com/:x:/g/personal/ciwan_ug_kth_se/EVZBa43qwv5cFYEruMLdlB4BuZBlUMRGzJEk7WaRttrhRg?e=xo7bDQ
  data_title: Ethereum data
  results_url: https://kth-my.sharepoint.com/:u:/g/personal/ciwan_ug_kth_se/EUsV-e2SpTleC9-AC8m9IRQBcsX0EasJ7u2MNUXeDhdRag?e=FQyqA4
  results_title: Results
